name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 222
        key: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/usr/home/nordld/nordlichter"
